### ISSUE TITLE
Prepare webkaos Docker image for working with K8s

### ISSUE THREAD

**Issue by igoradamenko** [essentialkaos/webkaos#120]
Hey there!

Currently a webkaos container can't utilize correctly the resources it gets from K8s, because it does not have a “worker tuning” like this one:

https://github.com/nginxinc/docker-nginx/blob/d496baf859613adfe391ca8e7615cc7ec7966621/mainline/alpine/30-tune-worker-processes.sh

It would be great if you could add it, because we rely on webkaos and want to use it in K8s 🤗

**Comment by andyone** [comment]
@igoradamenko Hi! I just want to tell you that I have released a [new version](https://hub.docker.com/r/essentialkaos/webkaos/tags) of Docker images with improved k8s support. So you can use the latest version of images from Docker Hub in your k8s instance.

If you have some questions or ideas about these images, I'll be glad to answer them.

**Comment by igoradamenko** [comment]
Yaay! Thank you 🎉
