### ISSUE TITLE
Feature: ngx_brotli support

### ISSUE THREAD

**Issue by gongled** [essentialkaos/webkaos#16]
@andyone what do you think about ngx_brotli compression support? From the one hand, I'm not sure that [google/ngx_brotli](https://github.com/google/ngx_brotli) and [cloudflare/ngx_brotli_module](https://github.com/cloudflare/ngx_brotli_module) are suitable for productions needs. From the other hand, brotli is already [supported in many modern browsers](http://caniuse.com/#feat=brotli), so would be nice to have this experimental feature in webkaos. Your opinion is very important for me.

**Comment by andyone** [comment]
I have thought about it before. I am confused by the lack of updates in ngx_brotli_module repository. Latest commit was more than 8 months ago.

**Comment by andyone** [comment]
`libbrotli` required for [google/ngx_brotli](https://github.com/google/ngx_brotli) was added in https://github.com/essentialkaos/kaos-repo/pull/105/commits/f22e2721b38a791c6c3589871a1a7590c213ee67 and now we can add this module to latest version of webkaos.

**Comment by andyone** [comment]
It looks like all those modules are abandoned.
