### ISSUE TITLE
Conflict with lib.lua

### ISSUE THREAD

**Issue by min1mal** [essentialkaos/webkaos#60]
Hi,

I have discovered this issue with Lua when updating on centos7 => http://prntscr.com/j2i3e5.

Some suggestions to fix it?

Best Regards

**Comment by andyone** [comment]
Hi! 

`lua` package was removed from release repository till the moment when rpm package will support this version. Now, an update should pass without any problems.

**Comment by min1mal** [comment]
Thanks for the effort.
