### ISSUE TITLE
Package webkaos doesn't provide webserver capability

### ISSUE THREAD

**Issue by dexoid** [essentialkaos/webkaos#91]
Hello!
We use webkaos webserver on clients servers.
We have a problem with phpmyadmin installation, because it depends on webserver capability.
But webkaos package doesn't provide webserver capability:
```
# repoquery --provides webkaos
#
```
For example, nginx package from epel repo:
```
# repoquery --provides nginx
config(nginx) = 1:1.16.1-1.el7
nginx = 1:1.16.1-1.el7
nginx(x86-64) = 1:1.16.1-1.el7
webserver
```
Phpmyadmin deplist:
```
# yum deplist phpmyadmin | grep webserver -A666
  dependency: webserver
   provider: nginx.x86_64 1:1.16.1-1.el7
   provider: lighttpd.x86_64 1.4.54-1.el7
   provider: httpd.x86_64 2.4.6-90.el7.centos
   provider: caddy.x86_64 0.11.4-1.el7
```
Could you add webserver capability to webkaos package?
See more:
https://docs.fedoraproject.org/ro/Fedora_Draft_Documentation/0.1/html/RPM_Guide/ch-dependencies.html#id662448

**Comment by andyone** [comment]
Hi! Thanks for reporting about it. I have released 1.17.4-1 with these changes:
```
$ repoquery --provides webkaos
webkaos = 1.17.4-1.el7
webkaos(x86-64) = 1.17.4-1.el7
webserver = 1.17.4-1.el7
```
